name: Spark Alchemy
baseurl: /spark-alchemy
description: Useful extensions to Apache Spark
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: Swoop, Inc
markdown: kramdown
